### ISSUE TITLE
[BUG] version number is wrong on flatpak

### ISSUE THREAD

**Issue by tectrixdev** [flathub/com.github.KRTirtho.Spotube#103]
see [#1827](https://github.com/KRTirtho/spotube/issues/1827)
and the issue still persists: https://flathub.org/apps/com.github.KRTirtho.Spotube

**Comment by Hydranet** [comment]
Will this fix the issue that the version is being displayed as 3.7.1 on Flathub and then update it to the most recent version, 3.8.2?
`Fixed no playback from the app due to recent change in YouTube API
`
https://github.com/KRTirtho/spotube/releases

**Comment by jojommeke** [comment]
If it gets fixed it will

**Comment by KRTirtho** [comment]
This has been fixed in upstream
