### ISSUE TITLE
Cant Log In my Last Fm account

### ISSUE THREAD

**Issue by DemonNinja999** [flathub/com.github.KRTirtho.Spotube#55]
I am not able to log in my Last FM account 
![SPOTUBE ISSUE](https://github.com/flathub/com.github.KRTirtho.Spotube/assets/102358464/3e20198c-1686-4131-b106-7008be1c8cf5)

**Comment by KRTirtho** [comment]
This is an upstream issue. Please search there. An issue already exists which has been fixed + released already
