### ISSUE TITLE
Please remove usages of branch property from manifests 

### ISSUE THREAD

**Issue by bbhtt** [flathub/com.github.KRTirtho.Spotube#83]
This will be blocked soon, this is a heads up for that

https://github.com/flathub/com.github.KRTirtho.Spotube/blob/1b0554b0731da908a854f8797370342be36deffd/com.github.KRTirtho.Spotube.yml#L169

should be a commit only or a tag or tag+commit

**Comment by KRTirtho** [comment]
Thanks for informing me. I'm already using the commit hash so I guess just removing the branch should sufficient to avoid the blockage

**Comment by KRTirtho** [comment]
Closing this as now we use commit SHA
